### ISSUE TITLE
Error opening an already saved path

### ISSUE THREAD

**Issue by stmolivier** [InnovaLangues/PathBundle#266]
When i reopen on a path, for which i provided steps, and saved, i have, on the left side : "There is no structure for this path.", and on the right side : only the modify button.
If i click on this modify button, the path is correctly loaded, but there is a problem though.

I also noticed when i loaded that page, i have this js error : 
```
XHR finished loading: GET "http://127.0.0.1/claroline512/bundles/innovapath/js/Step/Partial/show.html". angular-js.js:5
TypeError: Cannot read property 'description' of null
    at new StepShowCtrl (http://127.0.0.1/claroline512/vendor/innovapath/wizards.js:99:251)
    at e (http://127.0.0.1/claroline512/vendor/angular/angular-js.js:2:10651)
    at Object.instantiate (http://127.0.0.1/claroline512/vendor/angular/angular-js.js:2:10768)
    at http://127.0.0.1/claroline512/vendor/angular/angular-js.js:4:5501
    at A.link (http://127.0.0.1/claroline512/vendor/angular/angular-js.js:19:771)
    at $ (http://127.0.0.1/claroline512/vendor/angular/angular-js.js:4:1811)
    at M (http://127.0.0.1/claroline512/vendor/angular/angular-js.js:2:22202)
    at g (http://127.0.0.1/claroline512/vendor/angular/angular-js.js:2:18628)
    at http://127.0.0.1/claroline512/vendor/angular/angular-js.js:2:18152
    at http://127.0.0.1/claroline512/vendor/angular/angular-js.js:2:19123 <div data-ng-view="" class="ng-scope"> angular-js.js:8
XHR finished loading: GET "http://127.0.0.1/claroline512/bundles/innovapath/js/PathNavigation/Partial/show-item.html". 
```

**Comment by stmolivier** [comment]
i can precise that it happens only when the path is not published (created, saved, reopened... but not published)
